# using an alpine node js image fo better performance
FROM node:24-alpine3.20

# this is a working directory
WORKDIR  /react-app


# copying the content of the root folder to react-app that locates inside of the container
COPY . /react-app


